### ISSUE TITLE
Debugger embeds outdated version of core

### ISSUE THREAD

**Issue by Morendil** [elm-lang/elm-reactor#104] opened 2015-05-03 08:12 UTC
The code below now (0.15) results in the following Javascript error when loaded with ?debug

    Cannot read property 'ctor' of undefined

Single-stepping under the JS debugger narrows down the source of the problem: the function "start" is translated into a JS function which is called, upon startup, with an undefined parameter.

    import Graphics.Element exposing (..)

    import Window
    import Signal
    import Signal.Extra

    start signal =
        {}

    update signal state =
        state

    display anything =
        empty

    inputs = Window.dimensions

    main =
        let states = Signal.Extra.foldp' update start inputs
        in Signal.map display states

This seems to be the same error that was fixed by https://github.com/elm-lang/core/commit/8ca34a7827598b87eb7511a943b6050f2408515a, part of core version 2.0.1, but the debugger still contains an older version of genericMerge. See https://github.com/Apanatshka/elm-signal-extra/issues/11 for more discussion.

**Comment by evancz** [comment] 2015-05-07 17:30
I think this is related to https://github.com/elm-lang/elm-compiler/issues/826 where different instances of Elm can clash with each other?

**Comment by jvoigtlaender** [comment] 2015-05-25 12:41
@evancz, I don't know whether that compiler issue you link to is responsible for this. But the observation here clearly is: When a bug is fixed in the `core` package, the debug mode of `elm-reactor` does not benefit from that bug fix. Instead, a program that runs fine with the fixed `core` version in normal mode will still crash in debug mode. Which makes the debug mode much less useful until the next version of `elm-reactor` is released (compiled with the fixed `core` version).

At the moment, this means that the currently released version of `elm-reactor` does not help with debugging code that uses `Signal.merge` (because of the bug that was fixed when going from 2.0.0 to 2.0.1 in `core`). As an example, consider this program:
```elm
import Time
import Graphics.Element

main = Signal.map (\t -> Graphics.Element.show (fromJust t)) (Signal.merge (Signal.map Just (Time.every 1000)) (Signal.constant Nothing))

fromJust (Just a) = a
```
This works fine in the normal mode of `elm-reactor`. But starting it in the debug mode of `elm-reactor` crashes immediately.

Would it be possible to just release a new version of `elm-reactor` compiled with `core-2.0.1`, without fixing the possible root cause of the mismatches in the compiler? For practical purposes, this would make the debug mode useful again.

**Comment by jvoigtlaender** [comment] 2015-05-27 19:07
I've locally compiled a version of `elm-reactor`'s `debug.js` that solves the above problem, by being based on `core-2.0.1` instead of `core-2.0.0`. Just replacing `debug.js` in `ELM_HOME/reactor/_reactor/` by that new version lets my example program above run successfully in debug mode (instead of crashing as with the official version of `debug.js` that is put in place by the installers). I'm pretty sure it will also solve @Morendil's case above, and other related cases involving `Signal.merge`.

@evancz, would it be okay to share that `debug.js` version, e.g., via the mailing list?

**Comment by Morendil** [comment] 2015-05-27 20:23
I for one would much appreciate that, lacking enough time to invest in recompiling Elm from source at the moment. Thanks for your efforts, Janis!

**Comment by jvoigtlaender** [comment] 2015-05-28 06:08
Laurent, an appropriate version of `debug.js` is now found [here](https://github.com/jvoigtlaender/elm-bin/blob/debugger/share/reactor/_reactor/debug.js) (as part of an effort to make the `npm` installer provide a version of `elm-reactor` with debug mode enabled).

That version differs only in two places from the currently "officially released" `debug.js`. Namely, it incorporates [this fix](https://github.com/elm-lang/core/commit/745f04b969ffa98b1b5408766baccb0e1cad2937) and [this fix](https://github.com/elm-lang/core/commit/8ca34a7827598b87eb7511a943b6050f2408515a). This should repair the problems with `Signal.merge` and `Signal.Extra.foldp'`, as well as apparently some other problem with `Time.delay`.

I also have another, even more changed version of `debug.js`. But it includes more recent, ongoing, possibly incomplete changes that are currently happening to `elm-reactor`, so I have no idea whether they are overall functioning. So better to just use the version with the above two clearly identified fixes.

Anyway, using the linked version to replace `ELM_HOME/reactor/_reactor/debug.js` should fix the current problems.

**Comment by jvoigtlaender** [comment] 2015-05-28 09:32
A more permanent place for the fixed `debug.js` is now [here](https://github.com/kevva/elm-bin/blob/1.5.1/share/reactor/_reactor/debug.js) (in the `npm` installer repo).

**Comment by evancz** [comment] 2016-06-06 22:49
This problem does not exist with 0.17 and I think we have learned how to avoid it in future versions.

**Closed by evancz** 2016-06-06 22:49 UTC
Labels: bug
