### ISSUE TITLE
Non-ASCII characters in code prevent hotswapping

### ISSUE THREAD

**Issue by jastice** [elm-lang/elm-reactor#43] opened 2014-10-26 11:31 UTC
Non-ASCII characters in code prevent hotswapping in the debugger.

* place any non-ASCII character anywhere in a source being watched by elm-reactor
* the code will not swap and throw an error in the JS console
* manually reloading does not show this problem

For example, save this as a utf-8 elm file, load it in the debugger and set it to hot-swap:

    main = asText "note"

Now, change a character to an umlaut:

    main = asText "nöte"

The debugger will not reload, and the javascript console throws an error: 

    Uncaught SyntaxError: Unexpected number

Remove the umlaut:

    main = asText "nute"

The code will reload fine.

**Comment by jastice** [comment] 2015-01-29 12:52
Verified that issue persists in Elm Platform 0.14.1

**Comment by vilterp** [comment] 2015-07-13 21:54
Closing as duplicate of #68, which has a more recent code example

**Closed by vilterp** 2015-07-13 21:54 UTC
